export interface Hotel {
  name: string;
  stars: 5;
  distanceKm: number;
  transport: string;
  neighborhood: string;
  highlights: string[];
  priceFrom: number;
  bookingUrl: string;
  googleMapsUrl: string;
}

export const GP_HOTELS: Record<string, Hotel[]> = {
  "Monte Carlo": [
    {
      name: "Hotel de Paris Monte-Carlo",
      stars: 5,
      distanceKm: 0.1,
      transport: "A pie desde la curva de la Casino",
      neighborhood: "Place du Casino, Montecarlo",
      highlights: ["Vistas directas al circuito", "Restaurante Louis XV (3 estrellas Michelin)", "Spa con piscina climatizada"],
      priceFrom: 2800,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hotel+de+Paris+Monte-Carlo&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hotel+de+Paris+Monte-Carlo",
    },
    {
      name: "Hotel Metropole Monte-Carlo",
      stars: 5,
      distanceKm: 0.2,
      transport: "2 minutos a pie del circuito",
      neighborhood: "Avenue de la Madone, Montecarlo",
      highlights: ["Spa Givenchy", "Piscina exterior con barra de bar", "Restaurante Joël Robuchon (2 estrellas Michelin)"],
      priceFrom: 1900,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hotel+Metropole+Monte-Carlo&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hotel+Metropole+Monte-Carlo",
    },
    {
      name: "Fairmont Monte Carlo",
      stars: 5,
      distanceKm: 0.3,
      transport: "Dentro del recinto del GP, acceso directo",
      neighborhood: "Playa de Mónaco, La Condamine",
      highlights: ["Terraza con vistas al Mediterráneo", "Piscina en la azotea", "Ubicación única en la curva del túnel"],
      priceFrom: 1500,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Fairmont+Monte+Carlo&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Fairmont+Monte+Carlo",
    },
    {
      name: "Columbus Monte Carlo",
      stars: 5,
      distanceKm: 0.8,
      transport: "10 min a pie o 3 min en taxi",
      neighborhood: "La Fontvieille, Mónaco",
      highlights: ["Diseño contemporáneo de línea minimalista", "Bar con cócteles de autor", "Terraza con vistas al puerto"],
      priceFrom: 950,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Columbus+Monte+Carlo&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Columbus+Monte+Carlo",
    },
  ],

  "Melbourne": [
    {
      name: "Crown Towers Melbourne",
      stars: 5,
      distanceKm: 3.5,
      transport: "10 min en taxi o Uber",
      neighborhood: "Southbank, orilla del Yarra",
      highlights: ["Piscina exclusiva en planta superior", "Spa de 3000 m²", "Casino y restaurantes premiados"],
      priceFrom: 850,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Crown+Towers+Melbourne&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Crown+Towers+Melbourne",
    },
    {
      name: "InterContinental Melbourne The Rialto",
      stars: 5,
      distanceKm: 4.0,
      transport: "12 min en taxi al Albert Park",
      neighborhood: "Collins Street, CBD",
      highlights: ["Edificio victoriano heritage de 1891", "Club Lounge con acceso privado", "Gimnasio 24h y spa"],
      priceFrom: 720,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=InterContinental+Melbourne+The+Rialto&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/InterContinental+Melbourne+The+Rialto",
    },
    {
      name: "Park Hyatt Melbourne",
      stars: 5,
      distanceKm: 4.2,
      transport: "12 min en taxi, shuttle disponible",
      neighborhood: "East Melbourne, junto al Fitzroy Gardens",
      highlights: ["Piscina climatizada", "Vistas al Melbourne Cricket Ground", "Restaurante The Dining Room galardonado"],
      priceFrom: 780,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Park+Hyatt+Melbourne&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Park+Hyatt+Melbourne",
    },
    {
      name: "Sofitel Melbourne On Collins",
      stars: 5,
      distanceKm: 4.0,
      transport: "12 min en taxi, metro Collins St",
      neighborhood: "Collins Street, CBD",
      highlights: ["Vistas panorámicas desde el piso 35", "Spa Le Club Med Gym", "Restaurante Atrium con desayuno gourmet"],
      priceFrom: 680,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Sofitel+Melbourne+On+Collins&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Sofitel+Melbourne+On+Collins",
    },
  ],

  "Shanghai": [
    {
      name: "Park Hyatt Shanghai",
      stars: 5,
      distanceKm: 28,
      transport: "35 min en metro línea 2 o 45 min en taxi",
      neighborhood: "Pudong, World Financial Center pisos 79-93",
      highlights: ["Hotel más alto de China", "Piscina en la nube a 85 plantas de altura", "Vistas 360° de Shanghái"],
      priceFrom: 950,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Park+Hyatt+Shanghai&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Park+Hyatt+Shanghai",
    },
    {
      name: "The Peninsula Shanghai",
      stars: 5,
      distanceKm: 30,
      transport: "40 min en taxi al circuito",
      neighborhood: "The Bund, Huangpu",
      highlights: ["Edificio heritage de 1906 en el Bund", "Spa de 1800 m²", "Restaurante Canton galardonado"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=The+Peninsula+Shanghai&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/The+Peninsula+Shanghai",
    },
    {
      name: "Waldorf Astoria Shanghai on the Bund",
      stars: 5,
      distanceKm: 30,
      transport: "40 min en taxi o metro línea 2",
      neighborhood: "The Bund, frente al río Huangpu",
      highlights: ["Vistas al Bund y Pudong", "Longbar histórico (el más largo de Asia)", "Spa Guerlain"],
      priceFrom: 1000,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Waldorf+Astoria+Shanghai+on+the+Bund&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Waldorf+Astoria+Shanghai+on+the+Bund",
    },
    {
      name: "Four Seasons Hotel Shanghai",
      stars: 5,
      distanceKm: 28,
      transport: "35 min en taxi, acceso directo al metro",
      neighborhood: "Jing'an, centro de Shanghái",
      highlights: ["Piscina climatizada interior", "Spa con tratamientos orientales", "Restaurante Shintaro de cocina japonesa"],
      priceFrom: 880,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Shanghai&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Shanghai",
    },
  ],

  "Suzuka": [
    {
      name: "Marriott Associa Nagoya",
      stars: 5,
      distanceKm: 30,
      transport: "30 min en tren JR Kansai Line hasta Suzuka",
      neighborhood: "Estación central de Nagoya",
      highlights: ["Directamente sobre la estación de Nagoya", "Vistas al Monte Fuji en días despejados", "Spa y piscina climatizada"],
      priceFrom: 650,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Marriott+Associa+Nagoya&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Marriott+Associa+Nagoya",
    },
    {
      name: "Hilton Nagoya",
      stars: 5,
      distanceKm: 31,
      transport: "30 min en tren desde Nagoya Station",
      neighborhood: "Sakae, centro de Nagoya",
      highlights: ["Bar en planta 29 con vistas panorámicas", "Piscina y fitness center", "Acceso fácil al metro de Nagoya"],
      priceFrom: 520,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hilton+Nagoya&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hilton+Nagoya",
    },
    {
      name: "Westin Nagoya Castle",
      stars: 5,
      distanceKm: 32,
      transport: "35 min en taxi o tren al circuito",
      neighborhood: "Junto al castillo de Nagoya",
      highlights: ["Vistas al castillo histórico de Nagoya", "Heavenly Bed y Spa Westin", "Restaurantes de cocina japonesa y occidental"],
      priceFrom: 490,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Westin+Nagoya+Castle&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Westin+Nagoya+Castle",
    },
  ],

  "Sakhir": [
    {
      name: "Four Seasons Hotel Bahrain Bay",
      stars: 5,
      distanceKm: 22,
      transport: "25 min en taxi al circuito",
      neighborhood: "Bahrain Bay, Manama",
      highlights: ["Piscina infinity con vistas al Golfo Pérsico", "Playa privada", "9 restaurantes y bares"],
      priceFrom: 1200,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Bahrain+Bay&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Bahrain+Bay",
    },
    {
      name: "The Ritz-Carlton Bahrain",
      stars: 5,
      distanceKm: 25,
      transport: "30 min en taxi, shuttle disponible durante el GP",
      neighborhood: "Manama Seef, frente al mar",
      highlights: ["Playa privada de 1 km", "Spa de 3200 m²", "Marina privada con actividades acuáticas"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=The+Ritz-Carlton+Bahrain&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/The+Ritz-Carlton+Bahrain",
    },
    {
      name: "Sofitel Bahrain Zallaq Thalassa Sea & Spa",
      stars: 5,
      distanceKm: 15,
      transport: "15 min en taxi, el más cercano al Bahrain International Circuit",
      neighborhood: "Zallaq, al-Riffa",
      highlights: ["Talasoterapia con agua de mar", "El hotel más cercano al circuito", "Playa privada y piscinas múltiples"],
      priceFrom: 900,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Sofitel+Bahrain+Zallaq&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Sofitel+Bahrain+Zallaq",
    },
  ],

  "Jeddah": [
    {
      name: "Four Seasons Hotel Jeddah at the Corniche",
      stars: 5,
      distanceKm: 2,
      transport: "5 min en taxi al Corniche Circuit",
      neighborhood: "Al Corniche, Jeddah",
      highlights: ["A 5 minutos del circuito urbano", "Piscina frente al Mar Rojo", "Spa de clase mundial con rituales árabes"],
      priceFrom: 1400,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Jeddah&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Jeddah+Corniche",
    },
    {
      name: "Rosewood Jeddah",
      stars: 5,
      distanceKm: 3,
      transport: "8 min en taxi al circuito",
      neighborhood: "Al Andalus, Jeddah Norte",
      highlights: ["Piscina infinity con vistas al Mar Rojo", "Spa Asaya con tratamientos orientales", "Restaurante Solea de alta cocina"],
      priceFrom: 1200,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Rosewood+Jeddah&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Rosewood+Jeddah",
    },
    {
      name: "Hyatt Regency Jeddah Corniche",
      stars: 5,
      distanceKm: 3,
      transport: "8 min en taxi al circuito urbano",
      neighborhood: "Al Corniche, Jeddah",
      highlights: ["Frente al mar Rojo en el paseo marítimo", "Club Regency con acceso preferente", "Piscina y fitness center"],
      priceFrom: 850,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hyatt+Regency+Jeddah+Corniche&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hyatt+Regency+Jeddah+Corniche",
    },
  ],

  "Miami Gardens": [
    {
      name: "Fontainebleau Miami Beach",
      stars: 5,
      distanceKm: 22,
      transport: "25 min en taxi o Uber al Hard Rock Stadium",
      neighborhood: "Mid-Beach, Miami Beach",
      highlights: ["Complejo de piscinas icónico de 4 acres", "Nightclub LIV (el más famoso de Miami)", "11 restaurantes y bares"],
      priceFrom: 1800,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Fontainebleau+Miami+Beach&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Fontainebleau+Miami+Beach",
    },
    {
      name: "Faena Hotel Miami Beach",
      stars: 5,
      distanceKm: 20,
      transport: "22 min en Uber al circuito",
      neighborhood: "Mid-Beach, Miami Beach",
      highlights: ["Diseño único de Philippe Starck y Baz Luhrmann", "Piscina cubierta con mamuts dorados", "Restaurante Pao de Paul Qui"],
      priceFrom: 1600,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Faena+Hotel+Miami+Beach&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Faena+Hotel+Miami+Beach",
    },
    {
      name: "The Setai Miami Beach",
      stars: 5,
      distanceKm: 19,
      transport: "20 min en taxi al Hard Rock Stadium",
      neighborhood: "South Beach, Miami Beach",
      highlights: ["3 piscinas de temperaturas distintas", "Ambiente asiático ultralujoso", "Restaurante The Restaurant con menú de autor"],
      priceFrom: 1500,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=The+Setai+Miami+Beach&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/The+Setai+Miami+Beach",
    },
    {
      name: "1 Hotel South Beach",
      stars: 5,
      distanceKm: 18,
      transport: "20 min en Uber, sin aparcamiento complicado",
      neighborhood: "South Beach, Collins Avenue",
      highlights: ["Hotel sostenible eco-luxury", "Rooftop pool con vistas al Atlántico", "Spa con tratamientos naturales"],
      priceFrom: 1300,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=1+Hotel+South+Beach+Miami&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/1+Hotel+South+Beach+Miami",
    },
  ],

  "Montréal": [
    {
      name: "Four Seasons Hotel Montreal",
      stars: 5,
      distanceKm: 8,
      transport: "15 min en taxi a la Île Notre-Dame",
      neighborhood: "Golden Square Mile, Downtown",
      highlights: ["Spa de 2500 m² con piscina cubierta", "Restaurante Marcus by Marcus Samuelsson", "Terraza con vistas al Mont Royal"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Montreal&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Montreal",
    },
    {
      name: "Ritz-Carlton Montreal",
      stars: 5,
      distanceKm: 9,
      transport: "15 min en taxi al circuito",
      neighborhood: "Sherbrooke Street West, Downtown",
      highlights: ["Edificio histórico de 1912 completamente renovado", "Spa con piscina y sauna", "Café de Paris, el restaurante más elegante de Montréal"],
      priceFrom: 950,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Ritz-Carlton+Montreal&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Ritz-Carlton+Montreal",
    },
    {
      name: "Hotel Le Crystal Montreal",
      stars: 5,
      distanceKm: 7,
      transport: "12 min en taxi, opción metro",
      neighborhood: "Quartier des spectacles, Centre-ville",
      highlights: ["Suites con cocina equipada", "Piscina cubierta en la azotea", "Céntrico a 5 min del Vieux-Montréal"],
      priceFrom: 680,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hotel+Le+Crystal+Montreal&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hotel+Le+Crystal+Montreal",
    },
  ],

  "Spielberg": [
    {
      name: "Sheraton Grand Salzburg",
      stars: 5,
      distanceKm: 55,
      transport: "50 min en coche al Red Bull Ring, shuttle disponible",
      neighborhood: "Auerspergstraße, Salzburgo centro",
      highlights: ["Piscina y spa en el centro de Salzburgo", "Junto al Mirabellgarten", "Ideal para combinar GP y Mozart"],
      priceFrom: 580,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Sheraton+Grand+Salzburg&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Sheraton+Grand+Salzburg",
    },
    {
      name: "Schloss Pichlarn",
      stars: 5,
      distanceKm: 25,
      transport: "25 min en coche al circuito",
      neighborhood: "Aigen im Ennstal, Estiria",
      highlights: ["Castillo histórico en plena naturaleza alpina", "Campo de golf de 18 hoyos", "Spa con piscina exterior"],
      priceFrom: 490,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Schloss+Pichlarn+Aigen&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Schloss+Pichlarn+Aigen+im+Ennstal",
    },
    {
      name: "Romantik Hotel Gmachl",
      stars: 5,
      distanceKm: 50,
      transport: "45 min en coche, zona de Salzburgo",
      neighborhood: "Elixhausen, Salzburgo",
      highlights: ["Hotel familiar de 6 generaciones", "Spa con 18 saunas diferentes", "Gastronomía austriaca de alta calidad"],
      priceFrom: 420,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Romantik+Hotel+Gmachl+Salzburg&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Romantik+Hotel+Gmachl+Elixhausen",
    },
  ],

  "Barcelona": [
    {
      name: "Hotel Arts Barcelona",
      stars: 5,
      distanceKm: 25,
      transport: "30 min en coche, autobús oficial GP desde la ciudad",
      neighborhood: "Vila Olímpica, frente al mar",
      highlights: ["Torre de 44 plantas junto a la playa", "Piscina infinity con vistas al Mediterráneo", "Spa Six Senses"],
      priceFrom: 900,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hotel+Arts+Barcelona&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hotel+Arts+Barcelona",
    },
    {
      name: "W Barcelona",
      stars: 5,
      distanceKm: 26,
      transport: "30 min en coche o autobús lanzadera GP",
      neighborhood: "Barceloneta, frente al mar",
      highlights: ["Diseño icónico en forma de vela", "Rooftop Eclipse bar con vistas 360°", "WET® deck con piscina exterior"],
      priceFrom: 850,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=W+Barcelona&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/W+Barcelona",
    },
    {
      name: "Mandarin Oriental Barcelona",
      stars: 5,
      distanceKm: 26,
      transport: "30 min en coche, Passeig de Gràcia con metro",
      neighborhood: "Passeig de Gràcia, Eixample",
      highlights: ["Rooftop pool con vistas a la Sagrada Família", "Spa con rituales orientales", "Restaurante Moments (2 estrellas Michelin)"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Mandarin+Oriental+Barcelona&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Mandarin+Oriental+Barcelona",
    },
    {
      name: "Casa Camper Barcelona",
      stars: 5,
      distanceKm: 27,
      transport: "30 min en coche o metro + lanzadera",
      neighborhood: "El Raval, centro histórico",
      highlights: ["Diseño nórdico-mediterráneo singular", "Snack bar gratuito 24 horas", "Habitaciones sin TV para desconectar"],
      priceFrom: 480,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Casa+Camper+Barcelona&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Casa+Camper+Barcelona",
    },
  ],

  "Silverstone": [
    {
      name: "Whittlebury Hall Hotel & Spa",
      stars: 5,
      distanceKm: 2,
      transport: "3 min en coche al circuito, el más cercano",
      neighborhood: "Whittlebury, Northamptonshire",
      highlights: ["A 2 km del circuito de Silverstone", "Spa de 3000 m² con 20 tratamientos", "Golf y actividades al aire libre"],
      priceFrom: 750,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Whittlebury+Hall+Hotel+Spa&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Whittlebury+Hall+Hotel+Spa+Northamptonshire",
    },
    {
      name: "The Belfry Hotel & Resort",
      stars: 5,
      distanceKm: 55,
      transport: "55 min en coche o shuttle desde Birmingham",
      neighborhood: "Sutton Coldfield, West Midlands",
      highlights: ["Campo de golf donde se han jugado 4 Ryder Cup", "Spa de lujo con piscina", "Amplia oferta de restaurantes"],
      priceFrom: 580,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=The+Belfry+Hotel+Resort&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/The+Belfry+Hotel+Resort+Sutton+Coldfield",
    },
    {
      name: "Whatley Manor Hotel and Spa",
      stars: 5,
      distanceKm: 65,
      transport: "65 min en coche por la M40",
      neighborhood: "Easton Grey, Malmesbury, Cotswolds",
      highlights: ["Manor house en plenos Cotswolds", "Spa Le Mazot con piscina cubierta", "Restaurante The Dining Room (1 estrella Michelin)"],
      priceFrom: 680,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Whatley+Manor+Hotel+Spa&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Whatley+Manor+Hotel+Spa+Malmesbury",
    },
  ],

  "Spa-Francorchamps": [
    {
      name: "Radisson Blu Palace Hotel Spa",
      stars: 5,
      distanceKm: 18,
      transport: "20 min en coche al circuito",
      neighborhood: "Place Royale, Spa ciudad",
      highlights: ["Históricas termas balnearias de Spa", "Spa y balnearioterapia con aguas termales", "Edificio belle époque rehabilitado"],
      priceFrom: 480,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Radisson+Blu+Palace+Hotel+Spa&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Radisson+Blu+Palace+Hotel+Spa+Belgium",
    },
    {
      name: "Crowne Plaza Liège",
      stars: 5,
      distanceKm: 40,
      transport: "40 min en coche o tren Liège-Spa + taxi",
      neighborhood: "Centro de Liège, Valonia",
      highlights: ["El mejor hotel de Liège", "Cercano a la estación de tren TGV", "Piscina cubierta y business center"],
      priceFrom: 320,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Crowne+Plaza+Liege&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Crowne+Plaza+Liège",
    },
    {
      name: "Château de Limont",
      stars: 5,
      distanceKm: 30,
      transport: "30 min en coche al circuito",
      neighborhood: "Limont, provincia de Liège",
      highlights: ["Castillo del siglo XIX en plena campiña belga", "Gastronomía belga de temporada", "Jardines históricos y tranquilidad"],
      priceFrom: 380,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Chateau+de+Limont+Belgium&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Château+de+Limont+Belgium",
    },
  ],

  "Budapest": [
    {
      name: "Four Seasons Hotel Gresham Palace Budapest",
      stars: 5,
      distanceKm: 22,
      transport: "25 min en taxi al Hungaroring",
      neighborhood: "Junto al Puente de las Cadenas, Pest",
      highlights: ["Palacio art nouveau restaurado de 1906", "Vistas al Danubio y al Castillo de Buda", "Spa y piscina cubierta"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Gresham+Palace+Budapest&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Gresham+Palace+Budapest",
    },
    {
      name: "Corinthia Hotel Budapest",
      stars: 5,
      distanceKm: 21,
      transport: "23 min en taxi, metro M2 disponible",
      neighborhood: "Erzsébetváros, Distrito VII",
      highlights: ["Edificio de 1896 con cúpula de cristal espectacular", "Spa Royal con piscina histórica", "Restaurante Brasserie & Bar galardonado"],
      priceFrom: 650,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Corinthia+Hotel+Budapest&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Corinthia+Hotel+Budapest",
    },
    {
      name: "Kempinski Hotel Corvinus Budapest",
      stars: 5,
      distanceKm: 22,
      transport: "25 min en taxi, acceso directo al metro",
      neighborhood: "Erzsébet tér, Centro de Pest",
      highlights: ["El hotel de lujo más moderno de Budapest", "Piscina cubierta y spa de 1800 m²", "Restaurante Nobu Budapest"],
      priceFrom: 700,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Kempinski+Hotel+Corvinus+Budapest&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Kempinski+Hotel+Corvinus+Budapest",
    },
  ],

  "Zandvoort": [
    {
      name: "Boutique Hotel Zuiderduin",
      stars: 5,
      distanceKm: 0.5,
      transport: "A pie desde el hotel al circuito",
      neighborhood: "Zandvoort, frente al Mar del Norte",
      highlights: ["A 500 metros del circuito", "Terraza con vistas al mar del Norte", "Spa con piscina de agua de mar"],
      priceFrom: 780,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hotel+Zuiderduin+Zandvoort&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hotel+Zuiderduin+Zandvoort",
    },
    {
      name: "Carlton Square Hotel Haarlem",
      stars: 5,
      distanceKm: 12,
      transport: "15 min en coche o tren directo Haarlem-Zandvoort",
      neighborhood: "Centro de Haarlem",
      highlights: ["En el corazón histórico de Haarlem", "Spa y piscina cubierta", "Restaurante con terraza en el Grote Markt"],
      priceFrom: 520,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Carlton+Square+Hotel+Haarlem&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Carlton+Square+Hotel+Haarlem",
    },
    {
      name: "Marriott Amsterdam",
      stars: 5,
      distanceKm: 30,
      transport: "30 min en tren directo Ámsterdam-Zandvoort",
      neighborhood: "Leidseplein, Ámsterdam centro",
      highlights: ["Céntrico en Ámsterdam con todo a mano", "Tren directo al circuito sin cambios", "Spa y gimnasio completo"],
      priceFrom: 620,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Marriott+Amsterdam&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Marriott+Amsterdam",
    },
  ],

  "Monza": [
    {
      name: "Villa d'Este",
      stars: 5,
      distanceKm: 30,
      transport: "35 min en coche por la SS36",
      neighborhood: "Cernobbio, Lago de Como",
      highlights: ["El hotel más famoso del Lago de Como", "Jardines del siglo XVI", "Piscina flotante en el lago"],
      priceFrom: 1800,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Villa+d%27Este+Cernobbio&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Villa+d'Este+Cernobbio+Como",
    },
    {
      name: "Grand Hotel Victoria Concept & Spa",
      stars: 5,
      distanceKm: 32,
      transport: "35 min en coche, Bellagio a orilla del lago",
      neighborhood: "Menaggio, Lago de Como",
      highlights: ["Vistas al Lago de Como desde todas las habitaciones", "Spa con piscina cubierta", "Gastronomía italiana de autor"],
      priceFrom: 950,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Grand+Hotel+Victoria+Menaggio&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Grand+Hotel+Victoria+Menaggio",
    },
    {
      name: "Villa Serbelloni",
      stars: 5,
      distanceKm: 35,
      transport: "40 min en coche, el punto más bello del lago",
      neighborhood: "Bellagio, Lago de Como",
      highlights: ["Villa histórica en la punta de Bellagio", "Dos piscinas exteriores e interior", "Spa con tratamientos exclusivos"],
      priceFrom: 1400,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Villa+Serbelloni+Bellagio&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Villa+Serbelloni+Bellagio+Como",
    },
  ],

  "Madrid": [
    {
      name: "Four Seasons Hotel Madrid",
      stars: 5,
      distanceKm: 15,
      transport: "20 min en taxi o metro línea 8 a IFEMA",
      neighborhood: "Canalejas, centro de Madrid",
      highlights: ["Rooftop pool con vistas a Madrid", "Spa de 2500 m²", "Restaurante Dani García"],
      priceFrom: 1200,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Madrid&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Madrid",
    },
    {
      name: "Mandarin Oriental Ritz Madrid",
      stars: 5,
      distanceKm: 16,
      transport: "20 min en taxi al IFEMA",
      neighborhood: "Paseo del Prado, Madrid centro",
      highlights: ["El palacio hotelero más legendario de Madrid", "Jardín del Ritz (el más bello de Madrid)", "Restaurante Deessa de Quique Dacosta (3 estrellas Michelin)"],
      priceFrom: 1500,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Mandarin+Oriental+Ritz+Madrid&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Mandarin+Oriental+Ritz+Madrid",
    },
    {
      name: "Rosewood Villa Magna",
      stars: 5,
      distanceKm: 15,
      transport: "18 min en taxi, Castellana directa al IFEMA",
      neighborhood: "Paseo de la Castellana, Salamanca",
      highlights: ["El favorito de los equipos de F1 en Madrid", "Spa con piscina cubierta", "Restaurante Velayos de alta cocina española"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Rosewood+Villa+Magna+Madrid&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Rosewood+Villa+Magna+Madrid",
    },
    {
      name: "Hotel Único Madrid",
      stars: 5,
      distanceKm: 15,
      transport: "20 min en taxi al recinto del GP",
      neighborhood: "Barrio de Salamanca, Madrid",
      highlights: ["Palacete del XIX en el barrio más exclusivo", "Jardín privado en el corazón de Madrid", "Restaurante Ramón Freixa (2 estrellas Michelin)"],
      priceFrom: 850,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Hotel+Unico+Madrid&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Hotel+Único+Madrid",
    },
  ],

  "Baku": [
    {
      name: "Four Seasons Hotel Baku",
      stars: 5,
      distanceKm: 1,
      transport: "A pie o 3 min en taxi al circuito urbano",
      neighborhood: "Boulevard del Mar Caspio, Baku",
      highlights: ["A 1 km de la pista urbana", "Piscina exterior con vistas al Mar Caspio", "Spa con hammam azerbaiyano"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Baku&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Baku",
    },
    {
      name: "JW Marriott Absheron Baku",
      stars: 5,
      distanceKm: 2,
      transport: "5 min en taxi al circuito",
      neighborhood: "Neftchilar Avenue, Baku centro",
      highlights: ["Vistas panorámicas al Mar Caspio", "Spa con piscina cubierta", "Restaurantes con cocina azerbaiyana contemporánea"],
      priceFrom: 750,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=JW+Marriott+Absheron+Baku&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/JW+Marriott+Absheron+Baku",
    },
    {
      name: "Fairmont Baku at the Flame Towers",
      stars: 5,
      distanceKm: 1.5,
      transport: "5 min en taxi, vistas directas al circuito",
      neighborhood: "Flame Towers, colina de Baku",
      highlights: ["Ubicado en las icónicas Flame Towers", "Piscina infinity con vistas al Mar Caspio y al circuito", "Spa de clase mundial"],
      priceFrom: 950,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Fairmont+Baku+Flame+Towers&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Fairmont+Baku+Flame+Towers",
    },
  ],

  "Marina Bay": [
    {
      name: "Marina Bay Sands",
      stars: 5,
      distanceKm: 0.3,
      transport: "A pie desde el hotel a la pista",
      neighborhood: "Marina Bay, dentro del recinto del GP",
      highlights: ["Infinity pool en la azotea más famosa del mundo", "Casino de clase mundial", "El hotel está literalmente en el circuito"],
      priceFrom: 2200,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Marina+Bay+Sands+Singapore&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Marina+Bay+Sands+Singapore",
    },
    {
      name: "The Fullerton Hotel Singapore",
      stars: 5,
      distanceKm: 1,
      transport: "5 min a pie o en taxi al circuito",
      neighborhood: "Fullerton Square, Marina Bay",
      highlights: ["Edificio neoclásico de 1928 frente al río Singapur", "Piscina en la azotea con vistas al GP", "Restaurante The Lighthouse de alta cocina"],
      priceFrom: 1400,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=The+Fullerton+Hotel+Singapore&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/The+Fullerton+Hotel+Singapore",
    },
    {
      name: "Capella Singapore",
      stars: 5,
      distanceKm: 8,
      transport: "15 min en taxi desde Sentosa Island",
      neighborhood: "Sentosa Island, Singapur",
      highlights: ["Resort tropical en isla privada", "Spa The Auriga con piscinas naturales", "Dos piscinas infinity rodeadas de selva"],
      priceFrom: 1600,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Capella+Singapore&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Capella+Singapore",
    },
    {
      name: "Raffles Hotel Singapore",
      stars: 5,
      distanceKm: 2,
      transport: "8 min en taxi al circuito",
      neighborhood: "Beach Road, Civic District",
      highlights: ["El hotel más legendario de Asia (1887)", "Donde nació el Singapore Sling", "Jardines tropicales y piscina patrimonial"],
      priceFrom: 1800,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Raffles+Hotel+Singapore&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Raffles+Hotel+Singapore",
    },
  ],

  "Austin": [
    {
      name: "Fairmont Austin",
      stars: 5,
      distanceKm: 18,
      transport: "20 min en Uber al COTA",
      neighborhood: "Congress Avenue, Downtown Austin",
      highlights: ["El hotel más grande de Texas", "Piscina en la azotea con vistas al Capitolio", "Spa con tratamientos de inspiración texana"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Fairmont+Austin&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Fairmont+Austin",
    },
    {
      name: "Four Seasons Hotel Austin",
      stars: 5,
      distanceKm: 18,
      transport: "20 min en Uber al Circuit of the Americas",
      neighborhood: "San Jacinto Boulevard, orilla del Lago Ladybird",
      highlights: ["Vistas al Lago Ladybird y al Capitolio de Texas", "Piscina exterior con bar", "Spa con influencias de la cultura local"],
      priceFrom: 1300,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Austin&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Austin",
    },
    {
      name: "W Austin",
      stars: 5,
      distanceKm: 17,
      transport: "18 min en Uber al COTA",
      neighborhood: "2nd Street District, Downtown Austin",
      highlights: ["Wet deck con piscina y DJ en directo", "AWAY Spa con tratamientos contemporáneos", "Acceso directo a la escena musical de Austin"],
      priceFrom: 900,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=W+Austin&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/W+Austin",
    },
  ],

  "Mexico City": [
    {
      name: "Four Seasons Hotel Mexico City",
      stars: 5,
      distanceKm: 12,
      transport: "20 min en taxi al Autódromo Hermanos Rodríguez",
      neighborhood: "Paseo de la Reforma, Juárez",
      highlights: ["Jardín interior tropical único en la ciudad", "Spa con rituales prehispánicos", "Restaurante Fifty Mils (el mejor bar de México)"],
      priceFrom: 1000,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Mexico+City&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Mexico+City",
    },
    {
      name: "Rosewood Mexico City",
      stars: 5,
      distanceKm: 10,
      transport: "18 min en taxi al circuito",
      neighborhood: "Colonia Juárez, Reforma",
      highlights: ["Diseño mexicano contemporáneo de lujo", "Rooftop con vistas al Ángel de la Independencia", "Spa con temazcal tradicional"],
      priceFrom: 1200,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Rosewood+Mexico+City&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Rosewood+Mexico+City",
    },
    {
      name: "St. Regis Mexico City",
      stars: 5,
      distanceKm: 10,
      transport: "18 min en taxi, cerca del Estadio Azteca",
      neighborhood: "Paseo de la Reforma 439, Cuauhtémoc",
      highlights: ["Torre de cristal sobre la avenida más emblemática", "King Cole Bar con su famoso Bloody Mary", "Spa con piscina cubierta"],
      priceFrom: 950,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=St+Regis+Mexico+City&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/St+Regis+Mexico+City",
    },
  ],

  "São Paulo": [
    {
      name: "Fasano São Paulo",
      stars: 5,
      distanceKm: 8,
      transport: "15 min en taxi al Autódromo José Carlos Pace",
      neighborhood: "Jardins, São Paulo",
      highlights: ["El hotel de referencia de la F1 en São Paulo", "Bar Baretto, punto de encuentro del paddock", "Restaurante Fasano (el mejor de Brasil)"],
      priceFrom: 900,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Fasano+Sao+Paulo&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Fasano+São+Paulo",
    },
    {
      name: "Unique Hotel São Paulo",
      stars: 5,
      distanceKm: 9,
      transport: "15 min en taxi a Interlagos",
      neighborhood: "Jardim Paulista, São Paulo",
      highlights: ["Arquitectura única en forma de barco", "Rooftop pool con vista 360° a São Paulo", "Skye Rooftop Bar, el más popular de la ciudad"],
      priceFrom: 700,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Unique+Hotel+Sao+Paulo&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Unique+Hotel+São+Paulo",
    },
    {
      name: "Grand Hyatt São Paulo",
      stars: 5,
      distanceKm: 7,
      transport: "12 min en taxi al circuito de Interlagos",
      neighborhood: "Berrini, São Paulo",
      highlights: ["Piscina olímpica y spa completo", "Restaurante Ibi de cocina contemporánea", "Conveniente para el centro empresarial de São Paulo"],
      priceFrom: 620,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Grand+Hyatt+Sao+Paulo&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Grand+Hyatt+São+Paulo",
    },
  ],

  "Las Vegas": [
    {
      name: "Wynn Las Vegas",
      stars: 5,
      distanceKm: 0.5,
      transport: "A pie por el Strip al circuito",
      neighborhood: "The Strip, Las Vegas Boulevard",
      highlights: ["El casino-hotel más premiado del mundo", "Piscina con playa artificial", "18 restaurantes de autor"],
      priceFrom: 2500,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Wynn+Las+Vegas&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Wynn+Las+Vegas",
    },
    {
      name: "Bellagio Las Vegas",
      stars: 5,
      distanceKm: 0.8,
      transport: "A pie por el Strip",
      neighborhood: "The Strip, Las Vegas Boulevard",
      highlights: ["Fuentes danzantes icónicas frente al circuito", "Conservatorio de flores y jardines", "Restaurant Row con 19 restaurantes premium"],
      priceFrom: 2200,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Bellagio+Las+Vegas&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Bellagio+Las+Vegas",
    },
    {
      name: "The Venetian Resort Las Vegas",
      stars: 5,
      distanceKm: 0.6,
      transport: "A pie al circuito de Las Vegas GP",
      neighborhood: "The Strip, Las Vegas Boulevard",
      highlights: ["El hotel más grande de Europa y América (7092 suites)", "Canal interior con góndolas", "Canyon Ranch Spa de 6000 m²"],
      priceFrom: 1900,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=The+Venetian+Resort+Las+Vegas&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/The+Venetian+Resort+Las+Vegas",
    },
    {
      name: "ARIA Resort & Casino",
      stars: 5,
      distanceKm: 1,
      transport: "10 min a pie por el Strip",
      neighborhood: "CityCenter, The Strip",
      highlights: ["Diseño vanguardista de Norman Foster", "Spa ARIA con 62 cabinas de tratamiento", "30 restaurantes y bares"],
      priceFrom: 1800,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=ARIA+Resort+Casino+Las+Vegas&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/ARIA+Resort+Casino+Las+Vegas",
    },
  ],

  "Lusail": [
    {
      name: "Four Seasons Hotel Doha",
      stars: 5,
      distanceKm: 15,
      transport: "18 min en taxi al Circuito de Losail",
      neighborhood: "Corniche de Doha, West Bay",
      highlights: ["Playa privada a orillas del Golfo Pérsico", "Piscina olímpica y spa de 2800 m²", "7 restaurantes y bares de lujo"],
      priceFrom: 1400,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Four+Seasons+Hotel+Doha&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Four+Seasons+Hotel+Doha",
    },
    {
      name: "Marsa Malaz Kempinski The Pearl Doha",
      stars: 5,
      distanceKm: 12,
      transport: "15 min en taxi al circuito",
      neighborhood: "The Pearl Qatar, Doha",
      highlights: ["Ubicado en la isla artificial The Pearl", "Playa privada y marina", "Spa con hammam árabe tradicional"],
      priceFrom: 1200,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Marsa+Malaz+Kempinski+The+Pearl+Doha&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Marsa+Malaz+Kempinski+The+Pearl+Doha",
    },
    {
      name: "The St. Regis Doha",
      stars: 5,
      distanceKm: 14,
      transport: "18 min en taxi al Losail Circuit",
      neighborhood: "West Bay, Corniche de Doha",
      highlights: ["Torre de 336 metros con vistas al Golfo", "Spa Remède con piscina cubierta", "Iridium Spa y Butler Service 24h"],
      priceFrom: 1100,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=The+St+Regis+Doha&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/The+St+Regis+Doha",
    },
  ],

  "Yas Marina": [
    {
      name: "Yas Viceroy Abu Dhabi",
      stars: 5,
      distanceKm: 0,
      transport: "El hotel está literalmente encima del circuito",
      neighborhood: "Yas Island, sobre el pit lane",
      highlights: ["El único hotel del mundo construido sobre un circuito de F1", "Cubierta luminosa que cambia de color", "Vistas directas al pit lane y la pista"],
      priceFrom: 2800,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Yas+Viceroy+Abu+Dhabi&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Yas+Viceroy+Abu+Dhabi",
    },
    {
      name: "W Yas Island Abu Dhabi",
      stars: 5,
      distanceKm: 1,
      transport: "5 min a pie al Yas Marina Circuit",
      neighborhood: "Yas Island, junto al circuito",
      highlights: ["WET deck con piscina frente al circuito", "AWAY spa con sauna y hammam", "Acceso a las instalaciones de Yas Island"],
      priceFrom: 1400,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=W+Yas+Island+Abu+Dhabi&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/W+Yas+Island+Abu+Dhabi",
    },
    {
      name: "Radisson Blu Hotel & Resort Yas Island",
      stars: 5,
      distanceKm: 2,
      transport: "8 min a pie al circuito",
      neighborhood: "Yas Island, Abu Dhabi",
      highlights: ["Acceso directo a Yas Waterworld y Ferrari World", "Piscina exterior con vistas al Golfo", "Opción más asequible en Yas Island"],
      priceFrom: 800,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Radisson+Blu+Yas+Island+Abu+Dhabi&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Radisson+Blu+Yas+Island+Abu+Dhabi",
    },
    {
      name: "Anantara Eastern Mangroves Abu Dhabi Hotel",
      stars: 5,
      distanceKm: 18,
      transport: "20 min en taxi al circuito",
      neighborhood: "Eastern Mangroves, Abu Dhabi",
      highlights: ["Vistas únicas a los manglares de Abu Dhabi", "Kayak entre manglares al amanecer", "Spa Anantara con tratamientos asiáticos"],
      priceFrom: 750,
      bookingUrl: "https://www.booking.com/searchresults.html?ss=Anantara+Eastern+Mangroves+Abu+Dhabi&checkin=&checkout=&aid=304142",
      googleMapsUrl: "https://www.google.com/maps/search/Anantara+Eastern+Mangroves+Abu+Dhabi",
    },
  ],
};
